"""user transcription connection

Revision ID: 29df673a1694
Revises: ff41a6a9b223
Create Date: 2023-06-26 21:16:12.272089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29df673a1694'
down_revision = 'ff41a6a9b223'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transcription', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcription', type_='foreignkey')
    op.drop_column('transcription', 'user_id')
    # ### end Alembic commands ###
