"""add columns for notes

Revision ID: 502c9176ac66
Revises: 
Create Date: 2023-06-12 23:56:53.024586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502c9176ac66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription', sa.Column('notes_url_gpt3', sa.String(length=256), nullable=True))
    op.add_column('transcription', sa.Column('notes_url_gpt4', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcription', 'notes_url_gpt4')
    op.drop_column('transcription', 'notes_url_gpt3')
    # ### end Alembic commands ###
