"""Added social media content table

Revision ID: fafd539db759
Revises: 
Create Date: 2023-06-13 14:08:54.004174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fafd539db759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('yt_url', sa.String(length=256), nullable=True),
    sa.Column('audio_url', sa.String(length=256), nullable=True),
    sa.Column('transcript_url', sa.String(length=256), nullable=True),
    sa.Column('notes_url_gpt4', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcription_id', sa.Integer(), nullable=True),
    sa.Column('tweet_gpt35', sa.Text(), nullable=True),
    sa.Column('tweet_thread_gpt35', sa.Text(), nullable=True),
    sa.Column('linkedin_post_gpt35', sa.Text(), nullable=True),
    sa.Column('tweet_gpt4', sa.Text(), nullable=True),
    sa.Column('tweet_thread_gpt4', sa.Text(), nullable=True),
    sa.Column('linkedin_post_gpt4', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_media_content')
    op.drop_table('transcription')
    # ### end Alembic commands ###
